# Generated by Django 3.0.1 on 2022-10-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='canton',
            field=models.CharField(default='Zürich', editable=False, max_length=80),
        ),
    ]
