# Generated by Django 3.0.1 on 2022-10-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packaging',
            options={'verbose_name_plural': 'Packaging'},
        ),
        migrations.AddField(
            model_name='packaging',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='weight',
            field=models.CharField(choices=[('1 Kg', '1 Kg'), ('500g', '500g'), ('250g', '250g'), ('100g', '100g'), ('1 ltr', '1 Ltr'), ('2 ltrs', '2 Ltrs'), ('ca. 250-350g', 'ca. 250-350g')], max_length=50),
        ),
    ]
