# Generated by Django 3.0.1 on 2022-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221005_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='packaging_type',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Bag', 'Bag'), ('Box', 'Box'), ('Bottle', 'Bottle'), ('Jar', 'Jar'), ('Plastic Wrap', 'Plastic Wrap'), ('Foil Wrap', 'Foil Wrap')], max_length=50),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='weight',
            field=models.CharField(choices=[('1 Kg', '1 Kg'), ('500g', '500g'), ('250g', '250g'), ('200g', '200g'), ('120g', '120g'), ('100g', '100g'), ('1 ltr', '1 Ltr'), ('390ml', '390ml'), ('500ml', '500ml'), ('ca. 250-350g', 'ca. 250-350g'), ('ca. 0.9-1.1kg', 'ca. 0.9 - 1.1kg'), ('10 pieces of 53g+', '10 pieces of 53g+')], max_length=50),
        ),
    ]
